# docker volume create fatcnt
# docker build -t fatcnt docker
# docker container create --mount source=fatcnt,target=/opt/share/fatcnt -p 22:22 -i -t --name fatcnt_src fatcnt
# docker container start --attach -i  fatcnt_src

FROM dtcooper/raspberrypi-os:bookworm


RUN apt-get update && apt-get upgrade
RUN apt-get install -y git sudo openssh-server cmake gcc g++ gdb bzip2 \
    libopenblas-dev liblapack-dev ffmpeg pkg-config \
    libavdevice-dev libavfilter-dev libavformat-dev \
    libavcodec-dev libswresample-dev libswscale-dev \
    libavutil-dev gpg code net-tools vim

RUN adduser fatcnt
RUN passwd fatcnt
RUN su fatcnt -c "git config --global user.name "Aaron" && git config --global user.email azzmosphere@gmail.com"